routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('menus', 'MenuController')->except(['show']);
    Route::put('orders/close-transaction/{order}', 'OrderController@closeTransaction')->name('orders.close');
    Route::resource('orders', 'OrderController')->except(['show']);
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Home</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h3 class="text-center">Halloo {{ auth()->user()->name }}</h3>
                    <hr>
                    <div class="text-center">
                        <a href="{{ route('menus.index') }}" class="btn btn-primary">Lihat Menu</a>
                        <a href="" class="btn btn-success">Buat Pesanan</a>
                        <a href="{{ route('orders.index') }}" class="btn btn-warning">Lihat Pesanan</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/menu-form.blade.php
@extends('layouts.app')

@section('content')
@php
    (empty($edit) ? $edit = false : $edit = true)
@endphp
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header">@if($edit) Ubah @else Tambah @endif Menu</div>
                <div class="card-body">
                    <form role="form" method="POST" action="@if($edit) {{ route('menus.update', ['menu' => $menu->id]) }} @else {{ route('menus.store') }} @endif">
                        @csrf

                        @if ($edit)
                        {{ method_field('PUT') }}
                        @endif
                        <div class="form-group">
                            <label class="control-label" for="title">NAMA MENU</label>
                            <input class="form-control" name="title" id="title" value="@if($edit) {{ $menu->title }} @else {{ old('title') }} @endif">
                            @if ($errors->any())
                            @if(isset($errors->messages()['title']))
                            <small class="form-text text-danger">
                                {{ implode(', ', $errors->messages()['title']) }}
                            </small>
                            @endif
                            @endif
                        </div>
                        <div class="form-group">
                            <label class="control-label">STATUS</label>
                            <div class="radio">
                                <label><input type="radio" name="status" value="AVAILABLE" @if($edit) @if($menu->status === 'AVAILABLE') checked @endif @else checked @endif> AVAILABLE</label>
                            </div>
                            <div class="radio">
                                <label><input type="radio" name="status" @if($edit) @if($menu->status === 'NOT_AVAILABLE') checked @endif @endif value="NOT_AVAILABLE"> NOT AVAILABLE</label>
                            </div>
                            @if ($errors->any())
                            @if(isset($errors->messages()['status']))
                            <small class="form-text text-danger">
                                {{ implode(', ', $errors->messages()['status']) }}
                            </small>
                            @endif
                            @endif
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">SIMPAN</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/menu.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Daftar Menu</div>
                <div class="card-body">
                    @if (auth()->user()->role === '1')
                    <div class="text-right">
                        <a href="{{ route('menus.create') }}" class="btn btn-primary">Tambah Menu</a>
                        <br><br>
                    </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama</th>
                                    <th>Status</th>
                                    @if (auth()->user()->role === '1')
                                    <th>Aksi</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($menus as $index => $item)
                                <tr>
                                    <td>{{ $index + 1 }}</td>
                                    <td>{{ $item->title }}</td>
                                    <td>{{ str_replace_first('_', ' ', $item->status) }}</td>
                                    @if (auth()->user()->role === '1')
                                    <td>
                                        <a href="{{ route('menus.edit', ['menu' => $item->id]) }}" class="btn btn-sm btn-warning">Ubah</a>
                                        <a href="{{ route('menus.destroy', ['menu' => $item->id]) }}" class="btn-delete btn btn-sm btn-danger">Hapus</a>
                                    </td>
                                    @endif
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.all.min.js"></script>
<script>
    $(function(){
        $('.btn-delete').on('click', function(e) {
            e.preventDefault();
            const delUrl = $(this).attr('href');
            Swal({
                title: 'Konfirmasi Hapus Data',
                showCancelButton: true,
                confirmButtonText: 'Hapus',
                showLoaderOnConfirm: true,
                preConfirm: (login) => {
                    return fetch(delUrl, {
                            method:"DELETE",
                            headers: {
                                'X-CSRF-TOKEN': "{{ csrf_token() }}",
                            },
                        })
                        .then(response => {
                            if (response.status != 200) {
                                Swal({
                                    type : 'error',
                                    title : 'Error',
                                    text : 'Ups, Terjadi Kesalahan',
                                    confirmButtonText: 'OK',
                                    preConfirm: () => location.reload()
                                });
                            }
                        })
                        .catch(() => {
                            Swal({
                                type : 'error',
                                title : 'Error',
                                text : 'Ups, Terjadi Kesalahan',
                                confirmButtonText: 'OK',
                                preConfirm: () => location.reload()
                            });
                        })
                },
                allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                if (result) {
                    Swal({
                        type : 'success',
                        title : 'Success',
                        text : 'Data Berhasil Dihapus',
                        confirmButtonText: 'OK',
                        preConfirm: () => location.reload()
                    });
                }
            })
        });
    });
</script>
@endsection

resources/views/order-form.blade.php
@extends('layouts.app')

@section('content')
@php
    (empty($edit) ? $edit = false : $edit = true)
@endphp
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header">@if($edit) Ubah @else Tambah @endif Order</div>
                <div class="card-body">
                    @if($edit)
                    <p>Nomer Transaksi : <b>{{ $order->transaction_code }}</b></p>
                    @endif
                    <form role="form" method="POST" action="@if($edit) {{ route('orders.update', ['order' => $order->id]) }} @else {{ route('orders.store') }} @endif">
                        @csrf

                        @if ($edit)
                        {{ method_field('PUT') }}
                        @endif
                        <div class="form-group">
                            <label class="control-label" for="table_number">Nomer Meja</label>
                            <input class="form-control" name="table_number" id="table_number" value="@if($edit) {{ $order->table_number }} @else {{ old('title') }} @endif">
                            @if ($errors->any())
                            @if(isset($errors->messages()['table_number']))
                            <small class="form-text text-danger">
                                {{ implode(', ', $errors->messages()['table_number']) }}
                            </small>
                            @endif
                            @endif
                        </div>
                        <div class="form-group">
                            <label class="control-label">Menu</label>
                            @foreach ($menus as $item)
                            <div class="checkbox">
                                <label><input name="menus[]" type="checkbox" value="{{ $item->id }}" @if($edit) @if($order->menus->contains('id', $item->id)) checked @endif @endif> {{ $item->title }}</label>
                            </div>
                            @endforeach
                            @if ($errors->any())
                            @if(isset($errors->messages()['menus']))
                            <small class="form-text text-danger">
                                {{ implode(', ', $errors->messages()['menus']) }}
                            </small>
                            @endif
                            @endif
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">SIMPAN</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/order.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Daftar Menu</div>
                <div class="card-body">
                    <div class="text-right">
                        <a href="{{ route('orders.create') }}" class="btn btn-primary">Tambah Menu</a>
                        <br><br>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <th>#</th>
                                <th>Nomer Order</th>
                                <th>Nomer Meja</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </thead>
                            <tbody>
                                @foreach ($orders as $index => $order)
                                <tr>
                                    <td>{{ $index + 1 }}</td>
                                    <td data-toggle="collapse" data-target="#accordion{{ $index }}" class="clickable" style="cursor:pointer; color:blue">{{ $order->transaction_code }}</td>
                                    <td>{{ $order->table_number }}</td>
                                    <td>{{ $order->status }}</td>
                                    <td>
                                        <a href="{{ route('orders.edit', ['order' => $order->id]) }}" class="btn btn-sm btn-warning">Edit</a>
                                        @if($order->status !== 'CLOSE' && auth()->user()->role === '1')
                                        <a href="{{ route('orders.close', ['order' => $order->id]) }}" class="btn btn-sm btn-primary btn-close" >Bayar</a>
                                        @endif
                                        @if(auth()->user()->role === '1')
                                        <a href="{{ route('orders.destroy', ['order' => $order->id]) }}" class="btn btn-sm btn-danger btn-delete">Hapus</a>
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="5" style="padding:0px;">
                                        <div id="accordion{{ $index }}" class="collapse" style="padding:10px;">
                                            <label>Menu: </label>
                                            <ol>
                                                @foreach ($order->menus as $item)
                                                <li>{{ $item->title }}</li>
                                                @endforeach
                                            </ol>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.all.min.js"></script>
<script>
    function swalInit(url, methodReq, title, buttonText, successMessage) {
        Swal({
            title: title,
            showCancelButton: true,
            confirmButtonText: buttonText,
            showLoaderOnConfirm: true,
            preConfirm: (login) => {
                return fetch(url, {
                        method: methodReq,
                        headers: {
                            'X-CSRF-TOKEN': "{{ csrf_token() }}",
                        },
                    })
                    .then(response => {
                        if (response.status != 200) {
                            Swal({
                                type : 'error',
                                title : 'Error',
                                text : 'Ups, Terjadi Kesalahan',
                                confirmButtonText: 'OK',
                                preConfirm: () => location.reload()
                            });
                        }
                    })
                    .catch(() => {
                        Swal({
                            type : 'error',
                            title : 'Error',
                            text : 'Ups, Terjadi Kesalahan',
                            confirmButtonText: 'OK',
                            preConfirm: () => location.reload()
                        });
                    })
            },
            allowOutsideClick: () => !Swal.isLoading()
        }).then((result) => {
            if (result) {
                Swal({
                    type : 'success',
                    title : 'Success',
                    text : successMessage,
                    confirmButtonText: 'OK',
                    preConfirm: () => location.reload()
                });
            }
        })
    }

    $(function(){
        $('.btn-delete').on('click', function(e) {
            e.preventDefault();
            const delUrl = $(this).attr('href');
            swalInit(delUrl, 'DELETE', 'Hapus Data', 'Hapus', 'Data Berhasil Dihapus');
        });

        $('.btn-close').on('click', function(e) {
            e.preventDefault();
            const delUrl = $(this).attr('href');
            swalInit(delUrl, 'PUT', 'Bayar Dan Tutup Order', 'Bayar', 'Data Terbayar');
        });
    });
</script>
@endsection